name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: ./tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Compiled main PDF
          path: tex/main.pdf
          if-no-files-found: error
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated compiled Latex PDF
          branch: main
          file_pattern: tex/main.pdf
          commit_options: '--no-verify --signoff'
          commit_user_name: My GitHub Actions Bot
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true
